# Generated by Django 4.2.3 on 2023-08-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='doctors.speciality'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='specialty_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
